from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd


def build_reviewer_candidates(
    df: pd.DataFrame,
    ensemble_score_col: str,
    agreement_col: str,
    output_path: str | Path,
    top_n: int = 100,
    enabled: bool = True,
) -> list[dict[str, Any]]:
    """Generate structured JSONL candidates for future LLM review."""
    if not enabled:
        print("Candidate generation is disabled.")
        return []

    # Take top N by ensemble score
    top_candidates = df.sort_values(ensemble_score_col, ascending=False).head(top_n)
    
    candidates = []
    for _, row in top_candidates.iterrows():
        candidate = {
            "schema_version": "reviewer_candidate_v1",
            "timestamp": str(row["timestamp"]),
            "asset": "BTC",
            "timeframe": "4h",
            "candidate_side": "LONG" if row[ensemble_score_col] > 0.5 else "WAIT",
            "quant_evidence": {
                "ensemble_probability": float(row[ensemble_score_col]),
                "ensemble_agreement": float(row[agreement_col]),
                "alpha_score_percentile": float(
                    row.get("combined_alpha_score", row.get("alpha_score_v1_14", 0.0))
                ),
                "probability_edge_over_50": float(row[ensemble_score_col] - 0.5),
                "historical_bucket_mean_forward_return": float(row.get("bucket_mean_return", 0.0)),
                "historical_bucket_mean_cost_adjusted_return": float(row.get("bucket_mean_cost_adj", 0.0)),
                "expected_cost": 0.003,
                "ml_models_agree": bool(row[agreement_col] > 0.7),
            },
            "regime_context": {
                "macro_regime": float(row["macro_regime_score"]),
                "derivatives_regime": float(row["derivatives_regime_score"]),
            },
            "risk_flags": {
                "regime_dependent_signal": bool(abs(row["macro_regime_score"]) > 0.5),
                "high_cost_environment": False,
                "model_disagreement": bool(row[agreement_col] < 0.6),
            },
            "system_recommendation": "REVIEW_ONLY" if row[ensemble_score_col] > 0.6 else "WAIT",
            "notes": ["Generated by Ensemble Signal Lab V1.16.1"]
        }
        candidates.append(candidate)
        
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, "w") as f:
        for c in candidates:
            f.write(json.dumps(c) + "\n")
            
    return candidates
