from __future__ import annotations


OHLCV_TRADES_FEATURE_COLUMNS_V7_8 = [
    "source",
    "venue",
    "market_type",
    "symbol",
    "timeframe",
    "event_ts",
    "close_ts",
    "available_ts",
    "decision_ts",
    "feature_available_ts",
    "feature_run_id",
    "source_ohlcv_sha256",
    "source_trades_manifest_sha256",
    "trade_source_type",
    "feature_schema_version",
    "open",
    "high",
    "low",
    "close",
    "volume",
    "quote_volume",
    "trade_count_ohlcv",
    "taker_buy_base_volume_ohlcv",
    "taker_buy_quote_volume_ohlcv",
    "agg_trade_count",
    "agg_trade_quantity_sum",
    "agg_trade_quote_quantity_sum",
    "agg_trade_price_min",
    "agg_trade_price_max",
    "agg_trade_price_mean",
    "agg_trade_price_std",
    "agg_trade_vwap",
    "agg_trade_first_price",
    "agg_trade_last_price",
    "agg_trade_price_change",
    "agg_trade_price_return",
    "agg_trade_quantity_mean",
    "agg_trade_quantity_std",
    "agg_trade_quantity_max",
    "agg_trade_large_trade_count",
    "agg_trade_large_trade_quantity_sum",
    "taker_buy_agg_count",
    "taker_sell_agg_count",
    "taker_buy_quantity",
    "taker_sell_quantity",
    "taker_buy_quote_quantity",
    "taker_sell_quote_quantity",
    "taker_buy_ratio_count",
    "taker_buy_ratio_quantity",
    "taker_buy_ratio_quote",
    "taker_imbalance_count",
    "taker_imbalance_quantity",
    "taker_imbalance_quote",
    "agg_trades_per_minute",
    "agg_quantity_per_minute",
    "agg_quote_quantity_per_minute",
    "avg_agg_trades_per_ohlcv_trade",
    "agg_trade_count_vs_ohlcv_trade_count_ratio",
    "agg_quantity_vs_ohlcv_volume_ratio",
    "agg_quote_vs_ohlcv_quote_volume_ratio",
    "agg_trade_count_lag_1",
    "agg_trade_count_rolling_mean_5",
    "agg_trade_count_rolling_mean_15",
    "agg_trade_count_rolling_mean_60",
    "agg_trade_count_zscore_60",
    "agg_quantity_rolling_mean_5",
    "agg_quantity_rolling_mean_15",
    "agg_quantity_rolling_mean_60",
    "agg_quantity_zscore_60",
    "taker_buy_ratio_quantity_lag_1",
    "taker_buy_ratio_quantity_rolling_mean_15",
    "taker_buy_ratio_quantity_rolling_mean_60",
    "taker_buy_ratio_quantity_zscore_60",
    "taker_imbalance_quantity_lag_1",
    "taker_imbalance_quantity_rolling_mean_15",
    "taker_imbalance_quantity_rolling_mean_60",
    "taker_imbalance_quantity_zscore_60",
    "intrabar_trade_price_range",
    "intrabar_vwap_to_close",
    "intrabar_last_to_first_return",
    "intrabar_price_std_to_range",
    "trade_flow_pressure",
    "trade_flow_pressure_zscore_60",
    "hour_utc",
    "day_of_week_utc",
    "is_weekend_utc",
    "warmup_row",
    "trades_feature_null_count",
    "trades_feature_error_count",
]

OHLCV_TRADES_METADATA_COLUMNS_V7_8 = OHLCV_TRADES_FEATURE_COLUMNS_V7_8[:15]

OHLCV_TRADES_OHLCV_BASE_COLUMNS_V7_8 = [
    "open",
    "high",
    "low",
    "close",
    "volume",
    "quote_volume",
    "trade_count_ohlcv",
    "taker_buy_base_volume_ohlcv",
    "taker_buy_quote_volume_ohlcv",
]

OHLCV_TRADES_VALUE_COLUMNS_V7_8 = OHLCV_TRADES_FEATURE_COLUMNS_V7_8[15:]

OHLCV_TRADES_FEATURE_FAMILIES_V7_8 = {
    "ohlcv_base_reference": OHLCV_TRADES_OHLCV_BASE_COLUMNS_V7_8,
    "trade_aggregation": [
        "agg_trade_count",
        "agg_trade_quantity_sum",
        "agg_trade_quote_quantity_sum",
        "agg_trade_price_min",
        "agg_trade_price_max",
        "agg_trade_price_mean",
        "agg_trade_price_std",
        "agg_trade_vwap",
        "agg_trade_first_price",
        "agg_trade_last_price",
        "agg_trade_price_change",
        "agg_trade_price_return",
        "agg_trade_quantity_mean",
        "agg_trade_quantity_std",
        "agg_trade_quantity_max",
        "agg_trade_large_trade_count",
        "agg_trade_large_trade_quantity_sum",
    ],
    "aggressor_taker_approximation": [
        "taker_buy_agg_count",
        "taker_sell_agg_count",
        "taker_buy_quantity",
        "taker_sell_quantity",
        "taker_buy_quote_quantity",
        "taker_sell_quote_quantity",
        "taker_buy_ratio_count",
        "taker_buy_ratio_quantity",
        "taker_buy_ratio_quote",
        "taker_imbalance_count",
        "taker_imbalance_quantity",
        "taker_imbalance_quote",
    ],
    "trade_intensity": [
        "agg_trades_per_minute",
        "agg_quantity_per_minute",
        "agg_quote_quantity_per_minute",
        "avg_agg_trades_per_ohlcv_trade",
        "agg_trade_count_vs_ohlcv_trade_count_ratio",
        "agg_quantity_vs_ohlcv_volume_ratio",
        "agg_quote_vs_ohlcv_quote_volume_ratio",
    ],
    "rolling_trade_features": [
        "agg_trade_count_lag_1",
        "agg_trade_count_rolling_mean_5",
        "agg_trade_count_rolling_mean_15",
        "agg_trade_count_rolling_mean_60",
        "agg_trade_count_zscore_60",
        "agg_quantity_rolling_mean_5",
        "agg_quantity_rolling_mean_15",
        "agg_quantity_rolling_mean_60",
        "agg_quantity_zscore_60",
        "taker_buy_ratio_quantity_lag_1",
        "taker_buy_ratio_quantity_rolling_mean_15",
        "taker_buy_ratio_quantity_rolling_mean_60",
        "taker_buy_ratio_quantity_zscore_60",
        "taker_imbalance_quantity_lag_1",
        "taker_imbalance_quantity_rolling_mean_15",
        "taker_imbalance_quantity_rolling_mean_60",
        "taker_imbalance_quantity_zscore_60",
    ],
    "microstructure_proxies": [
        "intrabar_trade_price_range",
        "intrabar_vwap_to_close",
        "intrabar_last_to_first_return",
        "intrabar_price_std_to_range",
        "trade_flow_pressure",
        "trade_flow_pressure_zscore_60",
    ],
    "temporal": [
        "hour_utc",
        "day_of_week_utc",
        "is_weekend_utc",
    ],
    "audit": [
        "warmup_row",
        "trades_feature_null_count",
        "trades_feature_error_count",
    ],
}


FORBIDDEN_OHLCV_TRADES_FEATURE_COLUMNS_V7_8 = {
    "future_return",
    "future_close",
    "label",
    "target",
    "prediction",
    "signal",
    "trading_signal",
    "strategy_signal",
    "order",
    "pnl",
    "backtest",
    "position_size",
    "profit",
}
