from __future__ import annotations

import json
import importlib.util
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = PROJECT_ROOT / "src"
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from galapagos.research.microstructure_data_contract_approval_intake.anti_tautology_audit import (  # noqa: E501
    AntiTautologyAudit,
)
from galapagos.research.microstructure_data_contract_approval_intake.safety_guard import (
    SafetyGuard,
)
from galapagos.research.microstructure_data_contract_approval_intake.test_quality_audit import (
    TestQualityAudit,
)
_SMOKE_SPEC = importlib.util.spec_from_file_location(
    "smoke_test_clean_zip", PROJECT_ROOT / "scripts/smoke_test_clean_zip.py"
)
assert _SMOKE_SPEC is not None and _SMOKE_SPEC.loader is not None
_SMOKE_MODULE = importlib.util.module_from_spec(_SMOKE_SPEC)
_SMOKE_SPEC.loader.exec_module(_SMOKE_MODULE)
get_commands_for_version = _SMOKE_MODULE.get_commands_for_version


V_NORM = "v1_81_16"
V_DISP = "V1.81.16"


def _read(path: str) -> str:
    return (PROJECT_ROOT / path).read_text(encoding="utf-8")


def test_release_zip_contains_clean_zip_ready_field():
    content = _read(f"scripts/run_microstructure_data_contract_approval_intake_corrective_{V_NORM}.py")
    assert '"clean_zip_ready_for_external_review": True' in content


def test_validator_rejects_release_zip_missing_clean_zip_ready():
    content = _read(f"scripts/validate_microstructure_data_contract_approval_intake_corrective_{V_NORM}_reports.py")
    assert '"clean_zip_ready_for_external_review": True' in content
    assert 'release.get(field) is not expected' in content


def test_validator_rejects_release_ready_false():
    content = _read(f"scripts/validate_microstructure_data_contract_approval_intake_corrective_{V_NORM}_reports.py")
    assert '"release_ready_for_external_review": True' in content
    assert "release_zip: {field}" in content


def test_validator_rejects_final_smoke_false():
    content = _read(f"scripts/validate_microstructure_data_contract_approval_intake_corrective_{V_NORM}_reports.py")
    assert '"final_smoke_passed": True' in content


def test_validator_rejects_final_audit_false():
    content = _read(f"scripts/validate_microstructure_data_contract_approval_intake_corrective_{V_NORM}_reports.py")
    assert '"final_audit_passed": True' in content


def test_validator_rejects_blocking_reason_present():
    content = _read(f"scripts/validate_microstructure_data_contract_approval_intake_corrective_{V_NORM}_reports.py")
    assert 'release.get("blocking_reason") is not None' in content


def test_smoke_v1_81_16_runs_validator_command():
    commands = get_commands_for_version(V_NORM)
    assert commands[0][1] == f"scripts/validate_microstructure_data_contract_approval_intake_corrective_{V_NORM}_reports.py"
    assert commands[0][-1] == V_NORM
    assert len(commands) == 3


def test_zip_embedded_release_report_is_ready():
    zip_path = PROJECT_ROOT / "projet-galapagos-v1.81.16-clean.zip"
    if not zip_path.exists():
        pytest.skip("V1.81.16 zip is generated after release packaging")
    with zipfile.ZipFile(zip_path) as archive:
        payload = json.loads(archive.read(f"reports/release_zip_{V_NORM}.json"))
    assert payload["release_ready_for_external_review"] is True
    assert payload["clean_zip_ready_for_external_review"] is True
    assert payload["blocking_reason"] is None


def test_zip_embedded_smoke_report_is_passing():
    zip_path = PROJECT_ROOT / "projet-galapagos-v1.81.16-clean.zip"
    if not zip_path.exists():
        pytest.skip("V1.81.16 zip is generated after release packaging")
    with zipfile.ZipFile(zip_path) as archive:
        payload = json.loads(archive.read(f"reports/zip_smoke_test_{V_NORM}.json"))
    assert payload["smoke_test_passed"] is True
    assert payload["smoke_failed_count"] == 0
    assert payload["smoke_passed_count"] == payload["smoke_commands_count"]


def test_release_fields_aligned_across_summary_latest_metrics_project_state():
    files = [
        PROJECT_ROOT / f"reports/research/microstructure_data_contract_approval_intake_corrective_summary_{V_NORM}.json",
        PROJECT_ROOT / "reports/current/latest_metrics.json",
        PROJECT_ROOT / "reports/PROJECT_STATE.json",
    ]
    existing = [path for path in files if path.exists()]
    if len(existing) != len(files):
        pytest.skip("V1.81.16 reports are generated by the run script")
    payloads = [json.loads(path.read_text(encoding="utf-8")) for path in files]
    for field in ["release_ready_for_external_review", "final_audit_passed", "final_smoke_passed", "clean_zip_ready_for_external_review"]:
        assert {payload[field] for payload in payloads} == {True}
    assert {payload["blocking_reason"] for payload in payloads} == {None}


def test_no_artificial_parametrize_range_padding_present():
    content = Path(__file__).read_text(encoding="utf-8")
    assert "parametrize(" + '"i", range(' not in content
    assert "parametrize(" + "'i', range(" not in content


def test_quality_audit_current_file_passes_without_forcing():
    result = TestQualityAudit().scan_test_file(Path(__file__))
    assert result["test_quality_passed"] is True
    assert result["forbidden_test_names_count"] == 0
    assert result["weak_tests_count"] == 0


def test_anti_tautology_audit_current_file_passes():
    result = AntiTautologyAudit().scan_file(Path(__file__))
    assert result["test_quality_passed"] is True
    assert result["tautological_tests_count"] == 0


def test_safety_guard_rejects_real_order_capability():
    result = SafetyGuard().check_safety({"real_orders_possible": True})
    assert result["safety_check_passed"] is False


def test_run_script_does_not_force_quality_results():
    content = _read(f"scripts/run_microstructure_data_contract_approval_intake_corrective_{V_NORM}.py")
    assert 'quality["test_quality_passed"] = True' not in content
    assert 'quality["quality_audit_results_forced"] = True' not in content


def test_release_clean_zip_has_v1_81_16_final_rebuild_path():
    content = _read("scripts/release_clean_zip.py")
    assert 'v_norm.startswith("v1_81_")' in content


def test_validator_rejects_smoke_failed_count():
    content = _read(f"scripts/validate_microstructure_data_contract_approval_intake_corrective_{V_NORM}_reports.py")
    assert 'smoke.get("smoke_failed_count") != 0' in content


def test_validator_rejects_safety_data_trading_violations():
    content = _read(f"scripts/validate_microstructure_data_contract_approval_intake_corrective_{V_NORM}_reports.py")
    assert '"network_executed": False' in content
    assert '"data_directory_writes_allowed": False' in content
    assert '"real_orders_possible": False' in content


def test_validator_rejects_json_non_finite_values():
    content = _read(f"scripts/validate_microstructure_data_contract_approval_intake_corrective_{V_NORM}_reports.py")
    assert "math.isfinite" in content


def test_smoke_commands_are_non_empty_for_v1_81_16():
    commands = get_commands_for_version(V_NORM)
    assert commands
    assert all(command for command in commands)
